import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LinedBackground from "@/components/ui/LinedBackground";

const ObjectSans = localFont({
  src: [
    {
      path: './fonts/ObjectSans-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ObjectSans-Heavy.otf',
      weight: '600',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Bishoy Morgan | Freelance Web Developer",
  description: "Generated by Morgan",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    
  return (
    <html lang="en">
      <body
        className={`${ObjectSans.className} antialiased`}
      >
        <LinedBackground />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
