import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ObjectSans = localFont({
  src: [
    {
      path: './fonts/ObjectSans-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    // {
    //   path: './fonts/ObjectSans-Slanted.otf',
    //   weight: '500',
    //   style: 'normal',
    // },
    {
      path: './fonts/ObjectSans-Heavy.otf',
      weight: '600',
      style: 'normal',
    },
    // {
    //   path: './fonts/ObjectSans-HeavySlanted.otf',
    //   weight: '700',
    //   style: 'normal',
    // },
  ],
})

export const metadata: Metadata = {
  title: "Morgan",
  description: "Generated by Morgan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ObjectSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
