import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LinedBackground from "@/components/ui/LinedBackground";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

const ObjectSans = localFont({
  src: [
    {
      path: './fonts/ObjectSans-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ObjectSans-Heavy.otf',
      weight: '600',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Bishoy Morgan | Freelance Web Developer",
  description: "Generated by Morgan",
};

const locales = ['en', 'es', 'ar'];

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!locales.includes(locale)) {
    notFound();
  }

const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body className={`${ObjectSans.className} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LinedBackground />
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
